export const CAMERA_MODES = {
  chase: {
    key: "1",
    label: "Tail chase",
    distance: 18,
    height: 5.5,
    lookAhead: 10,
    focusHeight: 0.6,
    birdLift: 1.0,
    speedPullback: 0.08,
    lag: 9.5,
    bankAmount: 0.16,
    fov: 58,
  },
  shoulder: {
    key: "2",
    label: "Over-shoulder",
    distance: 14,
    height: 3.2,
    lateral: 3.0,
    lookAhead: 8,
    focusHeight: 0.8,
    birdLift: 1.0,
    lag: 10,
    bankAmount: 0.28,
    fov: 60,
  },
  fpv: {
    key: "3",
    label: "Crow vision",
    distance: 0.6,
    height: 0.35,
    lookAhead: 12,
    lag: 11,
    bankAmount: 0.12,
    fov: 72,
  },
  commander: {
    key: "4",
    label: "Top-down",
    distance: 48,
    height: 42,
    lookAhead: 0,
    focusHeight: 0.5,
    lag: 5,
    bankAmount: 0,
    fov: 48,
  },
};

export const MODE_ORDER = ["chase", "shoulder", "fpv", "commander"];
